# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Orange & Bronze University
email: info@orangeandbronze.com
contact_number: (63) 2 478-9999
contact_number_2: (63) 2 856-5770
fax_number: +632 751.47.26
address_ph: "Philippines: 3rd Floor, CJV Building
108 Aguirre Street, Legaspi Village, 
Makati City, Philippines 1229"
keywords: java training philippines, java classes philippines, spring training philippines, hibernate training philippines, java courses philippines, spring courses philippines, hibernate courses philippines, agile classes philippines, java training company philippines, android training philippines, android courses philippines, agile training philippines, agile courses philippines, hibernate classes philippines, java philippines, javabootcamp philippines, java bootcamp manila, scrum training manila, agile philippines, spring development training philippines, scrum and agile training philippines
description: Our training courses were developed using knowledge gained from real-world software development projects. We offer classes in Java, Spring, Hibernate, Agile, and other related technologies.
baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://university.orangeandbronze.com" # the base hostname & protocol for your site, e.g. http://example.com
facebook_username: orangeandbronze
googleplus_username: +orangeandbronze
twitter_username: orangeandbronze
linkedin_username:  orange-and-bronze-software-labs

# Build settings
markdown: kramdown

permalink: pretty
permalink: /:categories/:title/

header_pages:
 - about.html

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
